# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: CmdLine@2
  inputs:
    script: |
      echo source branch is $(Build.SourceBranch)
      git remote add github https://github.com/liefuzhang/heroku-test.git
      git remote add origin https://LiefuZhang@dev.azure.com/LiefuZhang/Liefu-Heroku-Test/_git/Liefu-Heroku-Test
      git featch origin
      git checkout -b $(Build.SourceBranch) origin/$(Build.SourceBranch)
      git push -u github $(Build.SourceBranch)
      echo pushed to github

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      curl \
        -X POST \
        -H "Authorization: token 6cb30a004824e9365c1e7ae956b23b6369190c5b" \
        https://api.github.com/repos/liefuzhang/heroku-test/pulls \
        -d '{"head":"$(Build.SourceBranch)","base":"master","title":"Merge $(Build.SourceBranch)"}'
    
