# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      curl --header "Authorization:token 6cb30a004824e9365c1e7ae956b23b6369190c5b" https://api.github.com/repos/liefuzhang/heroku-test
      curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/liefuzhang/heroku-test/pulls \
        -d '{"head":"feature/dd","base":"master"}'
    
