trigger:
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: CmdLine@2
  inputs:
    script: |
      echo Creating Pull Request for feature/test in github      
      response=$(curl \
        -X POST \
        -H "Authorization: token $(GITHUB_TOKEN)" \
        https://api.github.com/repos/liefuzhang/heroku-test/pulls \
        -d '{"head":"feature/test","base":"master","title":"Merge feature/test"}' | jq -r '.number') 
      echo response is $response
      echo "##vso[task.setvariable variable=PullNumber;]$response"
  displayName: Create Pull Request for feature/test in github 
    
- task: CmdLine@2
  displayName: Post Message to PR
  inputs:
    script: |
      echo Post Message to PR
      $url = "$(System.TeamFoundationCollectionUri)$(System.TeamProjectId)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=5.1"
      echo $url is $(url)
      curl \
        -X POST \
        -H "Authorization: token $(System.AccessToken)" \
        $(url) \
        -d '{"comments": [{"parentCommentId": 0,"content": "test","commentType": 1}]}'