# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: PowerShell@2
  displayName: "Complete github pull request step 1"
  inputs:
    targetType: "inline"
    script: |                      
      $organization = "LiefuZhang"
      $project = "Liefu-Heroku-Test"
      $repositoryId = "Liefu-Heroku-Test" 
      $pullRequestThreadUrl = "https://dev.azure.com/$organization/$project/_apis/git/repositories/$repositoryId/pullRequests/$(System.PullRequest.PullRequestId)/properties?api-version=6.0-preview.1"

      $result = Invoke-RestMethod -Uri $pullRequestThreadUrl -Method Get -ContentType "application/json" -Headers @{Authorization = "Bearer $(System.AccessToken)"}
    
      $pullNumber = $result.value.sampleId.'$value'
      Write-Host pullNumber is $pullNumber
      echo "##vso[task.setvariable variable=PullNumber]$pullnumber"

- task: CmdLine@2
  displayName: "Complete github pull request step 2"
  inputs:
    script: |
      curl \
        -X PUT \
        -H "Authorization: token $(GITHUB_TOKEN)" \
        https://api.github.com/repos/liefuzhang/heroku-test/pulls/$(PullNumber)/merge'