trigger:
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: CmdLine@2
  displayName: Post Message to PR
  inputs:
    script: |
      echo Post Message to PR
      curl \
        -X POST \
        -H "Authorization: token $(System.AccessToken)" \
        $(System.TeamFoundationCollectionUri)$(System.TeamProjectId)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/26/threads?api-version=5.1 \
        -d '{"comments": [{"parentCommentId": 0,"content": "test","commentType": 1}]}'