# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: CmdLine@2
  displayName: Push master to github
  inputs:
    script: |
      git remote add github https://github.com/liefuzhang/heroku-test.git
      git fetch origin
      git checkout -b master origin/master
      git push https://$(GITHUB_TOKEN)@github.com/liefuzhang/heroku-test.git master