name: CI

on:
  push:
    branches:
    - master

jobs:
  build_heroku-test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'my-identitytest' }}
      run: |
        cd ./ASPNetCoreLabs/HerokuContainer
        docker login --username=liefuzhangnz@gmail.com --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
 
